#!/bin/bash

echo $$ > marvin.pid
while [ true ]
do
   function traverse {
     for f in $1/*
     do
         if [ -f $f ]; then
             source $f
         elif [ -d $f ]; then
             traverse $f
         fi
     done
   }
 
   LIB="../lib"
   traverse $LIB
 
   NAME="$(capacities.get_info user.name)"
   if [[ ! "$NAME" -eq -1 ]]; then
        capacities.tell "Hello $NAME, what could I do for you?"
   else
        capacities.tell "Hello, I'm Marvine, what could I do for you?"
   fi
 
   while true; do read -p "Say something : "
        echo $REPLY | awk -F "( and )|( nd ) |( n )" '{
        for(i=1;i<=NF;i++) system("./brain "$i)
        }' 
   done;

done
