#!/bin/bash

echo $$ > marvin.pid
while [ true ]
do
   function traverse {
     for f in $1/*
     do
         if [ -f $f ]; then
             source $f
         elif [ -d $f ]; then
             traverse $f
         fi
     done
   }
 
   LIB="../lib"
   traverse $LIB
 
   NAME="$(capacities.get_info user.name)"
   if [[ ! "$NAME" -eq -1 ]]; then
        capacities.tell "Hello $NAME, what could I do for you?"
   else
        capacities.tell "Hello, I'm Marvine, what could I do for you?"
   fi

   while true; do read -p "Say something : " REPLY
       AWKPATTERN="( and )|( nd )|( n )|( 'n )|( 'nd )|( && )|( & )"
        NUMREQ=$(echo $REPLY | awk -F "$AWKPATTERN" '{ print NF }')  
        if [[ "NUMREQ" -eq 0 ]] || [[ "NUMREQ" -eq 1 ]]; then
            ./brain $REPLY
        elif [[ "NUMREQ" -gt 1 ]]; then
            for (( c=1; c<=$NUMREQ; c++ ))
            do
                CMD=$(echo "$REPLY" | awk -F "$AWKPATTERN" '{ print $'$c' }')
                #CMD=$(echo "$REPLY" | awk -F "( and )|( nd )|( n )" '{ print $'$c' }')
                ./brain "$CMD"
            done
        fi
   done

done
