#!/bin/bash

echo $$ > marvin.pid
while [ true ]
do
   function traverse {
     for f in $1/*
     do
         if [ -f $f ]; then
             source $f
         elif [ -d $f ]; then
             traverse $f
         fi
     done
   }
 
   LIB="../lib"
   traverse $LIB
 
   capacities.tell "Hello, I'm Marvine, what could I do for you?"
 
   while true; do read -p ""
   ./brain "$REPLY"
   done;

done
