#!/bin/bash

 
#get libraries
   
#get database
sudo apt-get install redis-server

#get database bash client
git clone https://github.com/caquino/redis-bash.git redis-bash

#make marvin
echo '#!/bin/bash

LIB="../lib"
COMMAND="$@"
NAME=$(./redis-bash/redis-bash-cli -h localhost GET username)

function traverse {
   for f in $1/*
   do
       if [ -f $f ]; then
           source $f
       elif [ -d $f ]; then
           traverse $f
       fi
   done
}

traverse $LIB

if [[ $COMMAND =~ "hello" ]]
then
    capacities.tell "hey!"
    capacities.ask "What is your name? "
    NAME="$REPLY"
    SAVE=$(./redis-bash/redis-bash-cli -h localhost SET username $NAME)
    capacities.tell "Ok, $NAME"
elif [[ $COMMAND =~ "help" ]]
then
    capacities.list-api
    capacities.indic "Done"
else
    capacities.tell "Sorry $NAME, I didnt get it"
fi


' > brain
chmod +x brain

echo '#!/bin/bash
cd core && ./start' > ../marvin
chmod +x ../marvin

