#!/bin/bash

 
#get libraries
   
#get database
sudo apt-get install redis-server

#get database bash client
git clone https://github.com/caquino/redis-bash.git redis-bash

#make marvin
echo '#!/bin/bash

function traverse {
   for f in $1/*
   do
       if [ -f $f ]; then
           source $f
       elif [ -d $f ]; then
           traverse $f
       fi
   done
}

LIB="../lib"
traverse $LIB

COMMAND="$@"
NAME=$(capacities.get_info "user.name")

capacities.understand "$COMMAND"

' > brain
chmod +x brain

echo '#!/bin/bash
cd core && ./start' > ../marvin
chmod +x ../marvin

